//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinh
    {
        public int Ma { get; set; }
        public string Logo { get; set; }
        public string CongTy { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Banner1 { get; set; }
        public string Banner2 { get; set; }
        public string Banner3 { get; set; }
        public string Banner4 { get; set; }
        public string Email { get; set; }
    }
}
