//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.PhieuNhapChiTiets = new HashSet<PhieuNhapChiTiet>();
            this.PhieuXuatChiTiets = new HashSet<PhieuXuatChiTiet>();
        }
    
        public int Ma { get; set; }
        public string Ten { get; set; }
        public string Mota { get; set; }
        public int MaLoai { get; set; }
        public string Anh { get; set; }
        public string Chitiet { get; set; }
        public Nullable<int> TieuBieu { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string ThuongHieu { get; set; }
        public string NhaSanXuat { get; set; }
        public Nullable<System.DateTime> NamSX { get; set; }
        public string GiamGia { get; set; }
        public Nullable<long> SoLuongTon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapChiTiet> PhieuNhapChiTiets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXuatChiTiet> PhieuXuatChiTiets { get; set; }
    }
}
